services:
  - type: web
    name: blog-app
    env: python-3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir /opt/render/project/src/blog-app ll_project.wsgi:application --bind 0.0.0.0:8000"
"
"
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/blog-app
      - key: DJANGO_SETTINGS_MODULE
        value: ll_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RDS_DB_NAME
        fromDatabase:
          name: your-database-service-name
          property: name
      - key: RDS_USERNAME
        fromDatabase:
          name: your-database-service-name
          property: user
      - key: RDS_PASSWORD
        fromDatabase:
          name: your-database-service-name
          property: password
      - key: RDS_HOSTNAME
        fromDatabase:
          name: your-database-service-name
          property: host
      - key: RDS_PORT
        fromDatabase:
          name: your-database-service-name
          property: port
