services:
  - type: web
    name: ll-project
    env: python-3.11
    region: oregon  # optional: specify the region (oregon is default)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ll_project.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ll_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RDS_DB_NAME
        fromDatabase:
          name: your-database-service-name
          property: name
      - key: RDS_USERNAME
        fromDatabase:
          name: your-database-service-name
          property: user
      - key: RDS_PASSWORD
        fromDatabase:
          name: your-database-service-name
          property: password
      - key: RDS_HOSTNAME
        fromDatabase:
          name: your-database-service-name
          property: host
      - key: RDS_PORT
        fromDatabase:
          name: your-database-service-name
          property: port
