# Generated by Django 5.0.4 on 2024-04-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
